from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a batch generation manifest from config and prompt pack."
    )
    parser.add_argument(
        "--config",
        type=str,
        required=True,
        help="Path to YAML config file.",
    )
    parser.add_argument(
        "--prompt-pack",
        type=str,
        required=True,
        help="Path to prompt_pack.csv generated by build_prompt_pack.py",
    )
    parser.add_argument(
        "--output-json",
        type=str,
        default="results/run_manifest.json",
        help="Path to save run manifest JSON.",
    )
    return parser.parse_args()


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_prompt_pack(path: Path) -> list[dict]:
    with path.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main() -> None:
    args = parse_args()

    config = load_yaml(Path(args.config))
    prompt_rows = load_prompt_pack(Path(args.prompt_pack))
    output_json = Path(args.output_json)
    output_json.parent.mkdir(parents=True, exist_ok=True)

    generation_cfg = config.get("generation", {})
    runtime_cfg = config.get("runtime", {})
    task_cfg = config.get("task", {})
    model_cfg = config.get("model", {})

    manifest = {
        "project_name": config.get("project", {}).get("name", "unknown_project"),
        "task_type": task_cfg.get("type", "unknown_task"),
        "asset_type": task_cfg.get("asset_type", "unknown_asset"),
        "model_family": model_cfg.get("family", "unknown_family"),
        "base_model_name": model_cfg.get("base_model_name", "unknown_model"),
        "seed": runtime_cfg.get("seed", 42),
        "width": generation_cfg.get("width", 1024),
        "height": generation_cfg.get("height", 1024),
        "num_inference_steps": generation_cfg.get("num_inference_steps", 30),
        "guidance_scale": generation_cfg.get("guidance_scale", 7.0),
        "sampler": generation_cfg.get("sampler", "unknown_sampler"),
        "scheduler": generation_cfg.get("scheduler", "unknown_scheduler"),
        "output_subdir": generation_cfg.get("output_subdir", "outputs/placeholder"),
        "items": [],
    }

    for row in prompt_rows:
        positive_prompt_path = Path(row["positive_prompt_path"])
        positive_prompt = positive_prompt_path.read_text(encoding="utf-8").strip()

        manifest["items"].append(
            {
                "id": row["id"],
                "subject": row["subject"],
                "style": row["style"],
                "attributes": row["attributes"],
                "positive_prompt": positive_prompt,
                "negative_prompt": row["negative_prompt"],
            }
        )

    with output_json.open("w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)

    print(f"[OK] Run manifest created: {output_json}")
    print(f"[OK] Number of generation items: {len(manifest['items'])}")
    print("[INFO] Current stage: manifest generation only, no direct ComfyUI execution yet.")


if __name__ == "__main__":
    main()